### ISSUE TITLE
Porting CP Geo Handbook to KACTL/Other Geo additions

### ISSUE THREAD

**Issue by Chillee** [kth-competitive-programming/kactl#77]
https://codeforces.com/blog/entry/56773
https://vlecomte.github.io/cp-geo.pdf

My main goal in doing this would be the following:
1. Add more tests for the geometry functions.
2. Reduce verbosity. Vlecomte's book has a lot of nice implementations, so I'll be picking the better one between the two.
3. Augment with some new functions. Namely, Halfplane.

For the sake of consistency (and because mostly there's not much of a difference...) I will be using the current KACTL Point class for everything.

- [x] Point.h
- [x] lineDistance.h (we could change it to `lineSqDist` so that it was exact for integers)
- [x] SegmentDistance.h 
- [x] SegmentIntersection.h
- [x] SegmentIntersectionQ.h
- [x] lineIntersection.h
- [x] sideOf.h
- [x] onSegment.h
- [x] linearTransformation.h
- [x] Angle.h
- [x] CircleIntersection.h Maybe update API to allow for returning 1.
- [ ] circleTangents.h
- [x] circumcircle.h
- [x] ~MinimumEnclosingCircle.h~
- [x] insidePolygon.h
- [x] PolygonArea.h
- [x] ~PolygonCenter.h~
- [x] ~PolygonCut.h~
- [x] ~ConvexHull.h~
- [x] ~PolygonDiameter.h~
- [x] ~PointInsideHull.h~
- [x] ~LineHullIntersection.h~
- [x] ~ClosestPair.h~
- [x] ~kdTree.h~
- [x] ~FastDelaunay.h~
- [x] PolyhedronVolume.h
- [x] Point3D.h
- [x] ~3dHull.h~
- [x] sphericalDistance.h

Potential new implementations that KACTL doesn't have (may move to separate issue):
- [ ] Circle-Line intersection
- [ ] Convex-Convex polygon intersection in `log n` time
- [ ] Max distance across convex polygon in `log n` time

**Comment by Chillee** [comment]
I have resolved all the issues/have a PR open, or plan on making a new issue for the new additions/major API changes (circleTangents.h).
